import logo from '../assets/logos/ux_research_copilot_logo_transparent.png';

export default function TermsPage({ onBack }) {
  return (
    <div style={{ minHeight: '100vh', background: 'linear-gradient(135deg, #F0F9FF 0%, #FFF9F5 100%)' }}>
      {/* Header */}
      <header style={{
        background: 'rgba(255, 255, 255, 0.8)',
        backdropFilter: 'blur(10px)',
        borderBottom: '1px solid #E5E7EB',
        padding: '2rem 0 1.5rem 0'
      }}>
        <div style={{ maxWidth: '1200px', margin: '0 auto', padding: '0 2rem' }}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '1rem' }}>
              <img src={logo} alt="UX Research Copilot" style={{ height: '140px' }} />
              <div>
                <p style={{
                  fontSize: '0.875rem',
                  color: '#6B7280',
                  margin: 0,
                  fontWeight: 500,
                  letterSpacing: '0.05em'
                }}>
                  AI-POWERED RESEARCH ANALYSIS
                </p>
              </div>
            </div>
            <button
              onClick={onBack}
              style={{
                padding: '0.5rem 1rem',
                backgroundColor: 'transparent',
                border: '1px solid #D1D5DB',
                borderRadius: '6px',
                cursor: 'pointer',
                color: '#6B7280',
              }}
            >
              Back to Home
            </button>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main style={{ maxWidth: '800px', margin: '0 auto', padding: '3rem 2rem' }}>
        <div className="card">
          <h1 style={{ fontSize: '2.5rem', fontWeight: 700, color: '#201E32', marginBottom: '1.5rem' }}>
            Terms of Service
          </h1>

          <div style={{ fontSize: '1rem', color: '#374151', lineHeight: 1.8 }}>
            <p style={{ marginBottom: '1.5rem', fontSize: '0.875rem', color: '#6B7280' }}>
              Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
            </p>

            <h2 style={{ fontSize: '1.5rem', fontWeight: 600, color: '#201E32', marginTop: '2rem', marginBottom: '1rem' }}>
              1. Acceptance of Terms
            </h2>
            <p style={{ marginBottom: '1.5rem' }}>
              By accessing and using UX Research Copilot, you accept and agree to be bound by these Terms of Service.
              If you do not agree to these terms, please do not use our service.
            </p>

            <h2 style={{ fontSize: '1.5rem', fontWeight: 600, color: '#201E32', marginTop: '2rem', marginBottom: '1rem' }}>
              2. Service Description
            </h2>
            <p style={{ marginBottom: '1.5rem' }}>
              UX Research Copilot is an AI-powered platform that analyzes research data and generates presentation-ready
              insights. We provide this service "as is" and make no guarantees about uptime, accuracy, or fitness for
              any particular purpose.
            </p>

            <h2 style={{ fontSize: '1.5rem', fontWeight: 600, color: '#201E32', marginTop: '2rem', marginBottom: '1rem' }}>
              3. User Responsibilities
            </h2>
            <p style={{ marginBottom: '1.5rem' }}>
              You are responsible for:
            </p>
            <ul style={{ marginBottom: '1.5rem', paddingLeft: '1.5rem' }}>
              <li>Maintaining the confidentiality of your account credentials</li>
              <li>Ensuring you have the right to upload and process the files you submit</li>
              <li>Complying with all applicable laws and regulations</li>
              <li>Using the service in a lawful and ethical manner</li>
            </ul>

            <h2 style={{ fontSize: '1.5rem', fontWeight: 600, color: '#201E32', marginTop: '2rem', marginBottom: '1rem' }}>
              4. Intellectual Property
            </h2>
            <p style={{ marginBottom: '1.5rem' }}>
              You retain all rights to the content you upload. The presentations and insights generated by our service
              are also your property. UX Research Copilot and its underlying technology remain our intellectual property.
            </p>

            <h2 style={{ fontSize: '1.5rem', fontWeight: 600, color: '#201E32', marginTop: '2rem', marginBottom: '1rem' }}>
              5. Prohibited Uses
            </h2>
            <p style={{ marginBottom: '1.5rem' }}>
              You may not:
            </p>
            <ul style={{ marginBottom: '1.5rem', paddingLeft: '1.5rem' }}>
              <li>Use the service for any illegal purpose</li>
              <li>Attempt to reverse engineer or copy our technology</li>
              <li>Upload malicious content or attempt to compromise our systems</li>
              <li>Share your account credentials with others</li>
            </ul>

            <h2 style={{ fontSize: '1.5rem', fontWeight: 600, color: '#201E32', marginTop: '2rem', marginBottom: '1rem' }}>
              6. Limitation of Liability
            </h2>
            <p style={{ marginBottom: '1.5rem' }}>
              UX Research Copilot is not liable for any damages arising from your use of the service, including but not
              limited to data loss, business interruption, or inaccurate AI-generated insights. You use the service at
              your own risk.
            </p>

            <h2 style={{ fontSize: '1.5rem', fontWeight: 600, color: '#201E32', marginTop: '2rem', marginBottom: '1rem' }}>
              7. Service Modifications
            </h2>
            <p style={{ marginBottom: '1.5rem' }}>
              We reserve the right to modify or discontinue the service at any time, with or without notice. We may also
              update these terms periodically.
            </p>

            <h2 style={{ fontSize: '1.5rem', fontWeight: 600, color: '#201E32', marginTop: '2rem', marginBottom: '1rem' }}>
              8. Termination
            </h2>
            <p style={{ marginBottom: '1.5rem' }}>
              We may terminate or suspend your access to the service at any time, for any reason, without notice.
            </p>

            <h2 style={{ fontSize: '1.5rem', fontWeight: 600, color: '#201E32', marginTop: '2rem', marginBottom: '1rem' }}>
              9. Contact
            </h2>
            <p style={{ marginBottom: '0' }}>
              Questions about these Terms of Service? Contact us at{' '}
              <a href="mailto:steinrueckn@gmail.com" style={{ color: '#C65D5D', textDecoration: 'none', fontWeight: 600 }}>
                steinrueckn@gmail.com
              </a>
            </p>
          </div>
        </div>
      </main>
    </div>
  );
}
